// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "weon":return img`
....fffff.....
...ff...ff....
..ff.....ff...
..f.......f...
..f.......f...
..ff.....ff..f
...ff...ff...f
....fffff...ff
......f....ff.
..ffffffffff..
.ff...f.......
ff....f.......
f.....f.......
f.....f.......
......f.......
......f..ff...
......f.fff...
.....ffff.f...
....ff....f...
...ff.....f...
...f..........
...f..........
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
